language: python
notifications:
  email: false
python:
  - 2.7
  - pypy
install:
  - pip install codecov
  - python setup.py install
script:
  coverage run -m unittest discover -s tests
after_success: codecov
